# Generated by Django 5.0.2 on 2024-10-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=12)),
                ('user_code_md5', models.CharField(default='', max_length=255)),
                ('password', models.CharField(max_length=250)),
                ('percentage_completed', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('fullname', models.CharField(max_length=255)),
            ],
        ),
    ]
