# Generated by Django 5.0.2 on 2024-10-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='percentage_completed',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='user_code_md5',
        ),
        migrations.AddField(
            model_name='studentuser',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='state',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterModelTable(
            name='studentuser',
            table='tb_user',
        ),
    ]
