# Generated by Django 5.0.2 on 2024-10-15 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_studentuser_percentage_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_name', models.CharField(max_length=255)),
                ('challenge_points', models.IntegerField()),
                ('challenge_time', models.DateTimeField()),
                ('challenge_type', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('state', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tb_challenges',
            },
        ),
        migrations.RenameModel(
            old_name='StudentUser',
            new_name='User',
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
            options={
                'db_table': 'tb_user_challenges',
                'unique_together': {('user', 'challenge')},
            },
        ),
    ]
