# Generated by Django 5.0.2 on 2024-10-15 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_challenge_rename_studentuser_user_userchallenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='date_created',
        ),
    ]
