# Generated by Django 5.0.2 on 2024-10-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_challenge_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accumulated_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='challenge_completed',
            field=models.IntegerField(default=0),
        ),
    ]
