# Generated by Django 5.0.2 on 2024-10-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_description', models.CharField(max_length=255)),
                ('shared_challenge_status', models.IntegerField()),
                ('approved_shared_challenge', models.IntegerField()),
                ('challenge_content', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'tb_detail_challenges',
            },
        ),
    ]
