# Generated by Django 5.0.2 on 2024-10-20 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_challengedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challenge_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.challengedetail'),
        ),
    ]
